"""improve application and interview relationships

Revision ID: eb1402c0e5ad
Revises: 2d4774ca397b
Create Date: 2026-09-09 20:40:27.333220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1402c0e5ad'
down_revision: Union[str, Sequence[str], None] = '2d4774ca397b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_application_job_candidate', 'applications', ['job_id', 'candidate_id'])
    op.drop_constraint(op.f('interview_sessions_application_id_key'), 'interview_sessions', type_='unique')
    op.create_index(op.f('ix_interview_sessions_application_id'), 'interview_sessions', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_sessions_application_id'), table_name='interview_sessions')
    op.create_unique_constraint(op.f('interview_sessions_application_id_key'), 'interview_sessions', ['application_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_application_job_candidate', 'applications', type_='unique')
    # ### end Alembic commands ###
